config/routes.rb
Rails.application.routes.draw do
  resources :sections do
    resources :lessons
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  belongs_to :section
  default_scope { order ("number ASC")}

  validates :name, :presence => true
  validates :content, :presence => true
  validates :number, :presence => true
end

app/models/section.rb
class Section < ActiveRecord::Base
  has_many :lessons
  
  validates :name, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  def show
    @lessons = Lesson.all
    @lesson = Lesson.find(params[:id])
  end

  def new
    @section = Section.find(params[:section_id])
    if @section.lessons.any?
      @lessonNumber = @section.lessons.last.number + 1
    else
      @lessonNumber = 1
    end
    @lesson = @section.lessons.new
  end

  def create
    @section = Section.find(params[:section_id])
    @lesson = @section.lessons.new(lesson_params)
    if @lesson.save
      redirect_to section_path(@lesson.section)
    else
      render :new
    end
  end

  def edit
    @lesson = Lesson.find(params[:id])
    @section = Section.find(params[:section_id])
  end

  def update
    @lesson = Lesson.find(params[:id])
    @section = @lesson.section
    if @lesson.update(lesson_params)
      redirect_to section_path(@lesson.section)
    else
      render :edit
    end
  end

  def destroy
    @lesson = Lesson.find(params[:id])
    @lesson.destroy
    redirect_to section_lessons_path(@lesson.section)
  end

  private
  def lesson_params
    params.require(:lesson).permit(:name, :content, :number, :dumb)
  end
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  def index
    @sections = Section.all
  end

  def show
    @section = Section.find(params[:id])
  end

  def new
    @section = Section.new
  end

  def create
    @section = Section.new(section_params)
    if @section.save
      redirect_to sections_path
    else
      render :new
    end
  end

  def edit
    @section = Section.find(params[:id])
  end

  def update
    @section = Section.find(params[:id])
    if @section.update(section_params)
      redirect_to section_path(@section)
    else
      render :edit
    end
  end

  def destroy
    @section = Section.find(params[:id])
    @section.destroy
    redirect_to sections_path
  end

  private
  def section_params
    params.require(:section).permit(:name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Learn How To Do Something</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <div class="jumbotron jumbotron-fluid">
      <div class="container">
        <h1 class="display-3">Learn How To Do Something</h1>
        <p class="lead">neat-o lessons on random STUFF!</p>
      </div>
    </div>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/lessons/_form.html.erb
<%= render "layouts/errors", :object => @lesson %>

<div class="form-group">
<%= form_for [@section, @lesson] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control" %>
  <%= f.label :content %>
  <%= f.text_area :content, class: "form-control", size: "24x6" %>
  <%= f.label :number %>
  <%= f.text_field :number, class: "form-control", value: @lessonNumber %>
  <%= f.submit class: "btn btn-primary" %>
<% end %>
</div>

app/views/lessons/edit.html.erb
<h1> Edit lesson </h1>

<%= render "form" %>

app/views/lessons/new.html.erb
<h1> New Lesson for <%= @section.name %> </h1>

<%= render "form" %>
<hr>
<%= link_to "Back to " + @section.name, section_path(@section) %>

app/views/lessons/show.html.erb
<h1><%= @lesson.name %></h1>
<h3><%= @lesson.content %></h3>

<p><%= link_to "Edit", edit_section_lesson_path(@lesson.section, @lesson) %></p>
<p><%= link_to "Delete", section_lesson_path(@lesson.section, @lesson),
                         :data => {:confirm => "You sure?",
                                   :method => "delete"} %></p>

<% @lessons.each do |lesson| %>
  <% if lesson.number == @lesson.number + 1 && lesson.section == @lesson.section %>
    <%= link_to "Next Lesson", section_lesson_path(lesson.section, lesson) %>
  <% elsif lesson.number == @lesson.number - 1 && lesson.section == @lesson.section %>
    <%= link_to "Previous Lesson", section_lesson_path(lesson.section, lesson) %>
  <% end %>
<% end %>

<% if !@lesson.dumb %>
  <%= form_for [@lesson.section, @lesson], :url => section_lesson_path, :html => {:moethd => :get} do |f| %>
    <%= f.hidden_field :dumb, :value => !@lesson.dumb %>
    <%= f.submit 'Flag this lesson as dumb', class: "btn btn-danger"%>
  <% end %>
<% else %>
  <h4>This lesson is dumb</h4>
<% end %>

<p><%= link_to "Return to " + @lesson.section.name + " lessons", section_path(@lesson.section) %></p>

app/views/sections/_form.html.erb
<%= render "layouts/errors", :object => @section %>

<div class="form-group">
  <%= form_for @section do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
    <%= f.submit class: "btn btn-primary" %>
  <% end %>
</div>

app/views/sections/edit.html.erb
<h1> Edit section </h1>

<%= render "form" %>

app/views/sections/index.html.erb
<h1>Sections</h1>

<%= select_tag 'section_id', options_from_collection_for_select(@sections, "id", "name"),:onchange => "window.location.replace('/sections/'+this.value);" %>

<hr>

<ul class="list-group">
  <% @sections.each do |section| %>
    <li class="list-group-item"><%= link_to section.name, section_path(section) %></li>
  <% end %>
</ul>

<%= link_to "Add a section", new_section_path %>

app/views/sections/new.html.erb
<h1> New Section </h1>

<%= render "form" %>

app/views/sections/show.html.erb
<h1><%= @section.name %></h1>

<% if @section.lessons.any? %>
  <h4>Lessons in this section:</h4>
  <ul class="list-group">
    <% @section.lessons.each do |lesson| %>
      <li class="list-group-item"><%= lesson.number %>. <%= link_to lesson.name, section_lesson_path(@section, lesson) %>
        <% if lesson.dumb %>
          <img src="https://cdn4.iconfinder.com/data/icons/smiley-2/54/smiley-face-avatar-shock-stupid-128.png" height="20" width="20" alt="dumb guy face">
        <% end %>
      </li>
    <% end %>
  </ul>
<% else %>
  <p>There are no lessons yet.</p>
<% end %>

<p><%= link_to "Add a lesson", new_section_lesson_path(@section) %></p>
<p><%= link_to "Edit Section", edit_section_path(@section) %></p>
<p><%= link_to "Delete Section", section_path(@section),
                        :data => {:confirm => "Are you sure?",
                                       :method => "delete"} %></p>
<p><%= link_to "Return to sections", sections_path %></p>